### PR TITLE
stablereq-find-candidates: Add --stabletime option

### PR DESCRIPTION
**Pull request by mattst88**
Signed-off-by: Matt Turner <mattst88@gentoo.org>

### CODE REVIEW

**Comment by mgorny** [comment]
I'm wondering if a generic `PKGCHECK_ARGS` (`file-pkgcheck` already has one) wouldn't be better. It definitely would be much simpler.

**Comment by mgorny** [comment]
Thanks. Could you also cover the remaining `stablereq-*` tools? Then feel free to push.

**Comment by mattst88** [comment]
(I cannot push, according to GitHub)

**Comment by mattst88** [comment]
Pushed as 4413fc3aa1b97828d94ef9ac6e15163d83d901fc

**Pull request closed without merging**
