### PR TITLE
Rename pkgdiff to pkgcmp to prevent collision with dev-util/pkgdiff

### PR DESCRIPTION
**Pull request by Flowdalic**
Signed-off-by: Florian Schmaus <flow@gentoo.org>

### CODE REVIEW

**Comment by Flowdalic** [comment]
It would be really great to be able to install dev-util/pkgdiff and your dev scripts at the same time. :)

**Comment by thesamesam** [comment]
Can't you just use diffoscope instead? :P

It's a shame to harm all of our muscle memories, but meh. I'd like to be able to use dev-util/pkgdiff too.

**Comment by Flowdalic** [comment]
> Can't you just use diffoscope instead? :P

Ha, thanks for the pointer. I was looking for tools to compare two archives and found pkgdiff, but was unable to emerge it due it being blocked by mgorny-dev-scripts. We may should consider mentioning diffoscope in devmanual (not that I believe I would have found it in that case, but it sure couldn't hurt).



> It's a shame to harm all of our muscle memories, but meh. I'd like to be able to use dev-util/pkgdiff too.

I don't have a strong opinion on this. This PR is basically just asking mgorny if he would consider changing the binaries name. I totally get that there a valid reasons to keep the name and to reject the PR.

**Comment by mgorny** [comment]
To be honest, I can't really think of a good solution. As @thesamesam pointed out, our muscle memory is strong, and unfortunately I wasn't aware of the problem until I've actually packaged it. I feel it's a bit late to change the name.

**Comment by Flowdalic** [comment]
That's perfectly fine, not unexpected and understandable.

**Comment by mgorny** [comment]
I suppose one option would be to rename and install a compat symlink under a USE flag.

**Comment by thesamesam** [comment]
https://github.com/projg2/mgorny-dev-scripts/commit/dbbdef4db0f8e7e11bf632be66b47106ee16a59c

**Pull request closed without merging**
